### ISSUE TITLE
User's Todo List

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/JQuery-Eval#1]
There will be two buttons 'Create User' and 'Create Todo', they will display respective forms.
1. User Form: It takes User's Name as input and display it in the User's column with it's initial remaining ToDo count as 0. Name should not be blank and should be unique.
2. ToDo Form: It takes todo as input with the assignee name from a select box which contains names of already existing user. Todo form will be displayed only if there is at least one user. It will alert an error message if somebody clicks on 'create todo' button and no user exists.

Once a task/todo is added, increment the count of remaining todos of the respective user who this task has been assigned to. Todo is displayed in the todo column with a checkbox. When this checkbox is checked then strike-through the todo which means that todo is done and the remaining todo count is decremented by 1 of the user. And if it unchecked increment the count by 1 again.

https://github.com/ayodeleDD/JQuery-Eval/blob/master/Todo/js/todo.js

**Comment by segunadeleye** [comment]
Create a different class that handles all input validation.

**Comment by segunadeleye** [comment]
I must commend you for code structure. Keep it up. You can only get better.

### Quick Observations:
- Make sure todos are not created when there are no users created yet. I changed the `display` value of the field and was able to create a todo.
- Also clear the todo input field after each todo is created.
- Have a method that handles binding events to elements rather than binding the events within the methods themselves.
- Look at breaking long codes into smaller chunks...if possible
- Some variables within a method are used just once, in this case, there is no need to save them in a variable.
- Make sure your Validator class is not too tightly coupled to the Todo class. Make the methods are generic as possible.

**Comment by ayodeleopetumo** [comment]
Validator class created and Issues fixed.

**Comment by segunadeleye** [comment]
![todo_layout](https://cloud.githubusercontent.com/assets/9962321/10716581/04783f9e-7b3e-11e5-99a0-88e896d4c2d5.png)
- Let's have a notification if a user tries to add a task when no user exists.
- Why pass `this.users` as an argument if it can be accessed directly by the methods
- Line 49 & 33: Do we really need this checks? Are they not redundant?
- Be more specific and descriptive with your method names. What exactly is `isFieldValid()` doing?
- If you remove `hidden` class, do you have to add the `show` class before the element can be visible?
- Line 89: where is `that` used?
- `titledName`, what if we still leave the variable name as `name`?
- The list of todos and the list of users both share same base. Can you fix this?

**Comment by ayodeleopetumo** [comment]
Issues fixed

**Comment by ayodeleopetumo** [comment]
Fixed the issue with the data attribute...please check

**Comment by segunadeleye** [comment]
All good
